export const SET_SEARCH_TERM = "SET_SEARCH_TERM";

export const SET_INTERVALS = "SET_INTERVALS";

export const IntervalsUpdatesActions = Object.freeze({
  BEGIN_FETCH_INTERVALS: "BEGIN_FETCH_INTERVALS",
  SUCCESS_FETCH_INTERVALS: "SUCCESS_FETCH_INTERVALS",
  FAIL_FETCH_INTERVALS: "FAIL_FETCH_INTERVALS "
});

export const DetailsGraphActions = Object.freeze({
  BEGIN_FETCH_DETAILS: "BEGIN_FETCH_DETAILS",
  SUCCESS_FETCH_DETAILS: "SUCCESS_FETCH_DETAILS",
  FAIL_FETCH_DETAILS: "FAIL_FETCH_DETAILS",
  SET_GRAPH_INTERVAL: "SET_GRAPH_INTERVAL",
  SET_GRAPH_ISSUE: "SET_GRAPH_ISSUE"
});

export const SET_PLANS_ISSUES = "SET_PLANS_ISSUES";
export const SELECT_PLANS_REPO = "SELECT_PLANS_REPO";
export const SELECT_PLANS_ISSUE = "SELECT_PLANS_ISSUE";
export const SET_PLANS_TIME = "SET_PLANS_TIME";
export const SET_PLANS_DATE = "SET_PLANS_DATE";
export const SET_ACTIVE_ISSUES = "SET_ACTIVE_ISSUES";
export const SET_HISTORICAL = "SET_HISTORICAL";
export const SET_DETAILS_INTERVAL = "SET_DETAIL_INTERVAL";
export const SET_DETAILS_ISSUE = "SET_DETAIL_ISSUE";
export const SET_DETIS_S_ISSUE = "SET_DETAIL_ISSUE";
export const SET_DETIISSUE = "SET_DETAIL_ISSUE";
export const SET_PLANS_REPOS = "SET_PLANS_REPOS";
